

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "80:8501"  # Expose Streamlit default port
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - .:/app  # Mount your app files
    networks:
      - app_net

networks:
  app_net:
