version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app_debug
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "streamlit", "run", "app.py", "--server.port=8501", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]
    ports:
      - "8501:8501"  # Expose Streamlit default port
      - "5676:5678"  # Expose 5676 on host and map to 5678 in the container
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - .:/app  # Mount your app files
    networks:
      - app_net

networks:
  app_net:
